package com.Wsdl2Code.WebServices.ServiceProviderBinding;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 10/12/2015 6:33:32 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.ServiceProviderBinding.WS_Enums.*;
import java.util.List;
import org.ksoap2.SoapEnvelope;
import org.ksoap2.SoapFault;
import org.ksoap2.serialization.SoapSerializationEnvelope;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.HeaderProperty;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import android.os.AsyncTask;
import org.ksoap2.serialization.MarshalFloat;

public class PatientBinding {

    public String NAMESPACE ="https://meetmdwcf.azurewebsites.net/API/XmlService.svc";
    public String url="";
    public int timeOut = 180;
    public IWsdl2CodeEvents eventHandler;
    public SoapProtocolVersion soapVersion;

    public PatientBinding(){}

    public PatientBinding(IWsdl2CodeEvents eventHandler)
    {
        this.eventHandler = eventHandler;
    }
    public PatientBinding(IWsdl2CodeEvents eventHandler,String url)
    {
        this.eventHandler = eventHandler;
        this.url = url;
    }
    public PatientBinding(IWsdl2CodeEvents eventHandler,String url,int timeOutInSeconds)
    {
        this.eventHandler = eventHandler;
        this.url = url;
        this.setTimeOut(timeOutInSeconds);
    }
    public void setTimeOut(int seconds){
        this.timeOut = seconds * 1000;
    }
    public void setUrl(String url){
        this.url = url;
    }
    public void PatientFillinSurveyAsync(AuthtokenXml authToken,String surveyId,VectorCustomerSurveyResultXml results) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientFillinSurveyAsync(authToken, surveyId, results, null);
    }

    public void PatientFillinSurveyAsync(final AuthtokenXml authToken,final String surveyId,final VectorCustomerSurveyResultXml results,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientFillinSurvey(authToken, surveyId, results, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientFillinSurvey", result);
                }
            }
        }.execute();
    }

    public void PatientFillinSurvey(AuthtokenXml authToken,String surveyId,VectorCustomerSurveyResultXml results){
        PatientFillinSurvey(authToken, surveyId, results, null);
    }

    public void PatientFillinSurvey(AuthtokenXml authToken,String surveyId,VectorCustomerSurveyResultXml results,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientFillinSurvey");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("surveyId",surveyId);
        soapReq.addProperty("results",results);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientFillinSurvey", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientFillinSurvey", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientCreateReminderAsync(AuthtokenXml authToken,PatientReminderXml reminder) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientCreateReminderAsync(authToken, reminder, null);
    }

    public void PatientCreateReminderAsync(final AuthtokenXml authToken,final PatientReminderXml reminder,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientCreateReminder(authToken, reminder, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientCreateReminder", result);
                }
            }
        }.execute();
    }

    public void PatientCreateReminder(AuthtokenXml authToken,PatientReminderXml reminder){
        PatientCreateReminder(authToken, reminder, null);
    }

    public void PatientCreateReminder(AuthtokenXml authToken,PatientReminderXml reminder,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientCreateReminder");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","reminder",new PatientReminderXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("reminder",reminder);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientCreateReminder", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientCreateReminder", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientRemoveReminderAsync(AuthtokenXml authToken,String reminderId) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientRemoveReminderAsync(authToken, reminderId, null);
    }

    public void PatientRemoveReminderAsync(final AuthtokenXml authToken,final String reminderId,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientRemoveReminder(authToken, reminderId, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientRemoveReminder", result);
                }
            }
        }.execute();
    }

    public void PatientRemoveReminder(AuthtokenXml authToken,String reminderId){
        PatientRemoveReminder(authToken, reminderId, null);
    }

    public void PatientRemoveReminder(AuthtokenXml authToken,String reminderId,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientRemoveReminder");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("reminderId",reminderId);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientRemoveReminder", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientRemoveReminder", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientGetRemindersAsync(AuthtokenXml authToken) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientGetRemindersAsync(authToken, null);
    }

    public void PatientGetRemindersAsync(final AuthtokenXml authToken,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, VectorPatientReminderXml>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorPatientReminderXml doInBackground(Void... params) {
                return PatientGetReminders(authToken, headers);
            }
            @Override
            protected void onPostExecute(VectorPatientReminderXml result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientGetReminders", result);
                }
            }
        }.execute();
    }

    public VectorPatientReminderXml PatientGetReminders(AuthtokenXml authToken){
        return PatientGetReminders(authToken, null);
    }

    public VectorPatientReminderXml PatientGetReminders(AuthtokenXml authToken,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientGetReminders");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetReminders", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetReminders", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorPatientReminderXml resultVariable = new VectorPatientReminderXml(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }

    public void PatientGetInfoAsync(AuthtokenXml authToken,int offset,boolean offsetSpecified,int limit,boolean limitSpecified) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientGetInfoAsync(authToken, offset, offsetSpecified, limit, limitSpecified, null);
    }

    public void PatientGetInfoAsync(final AuthtokenXml authToken,final int offset,final boolean offsetSpecified,final int limit,final boolean limitSpecified,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, VectorInfoRecordXml>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorInfoRecordXml doInBackground(Void... params) {
                return PatientGetInfo(authToken, offset, offsetSpecified, limit, limitSpecified, headers);
            }
            @Override
            protected void onPostExecute(VectorInfoRecordXml result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientGetInfo", result);
                }
            }
        }.execute();
    }

    public VectorInfoRecordXml PatientGetInfo(AuthtokenXml authToken,int offset,boolean offsetSpecified,int limit,boolean limitSpecified){
        return PatientGetInfo(authToken, offset, offsetSpecified, limit, limitSpecified, null);
    }

    public VectorInfoRecordXml PatientGetInfo(AuthtokenXml authToken,int offset,boolean offsetSpecified,int limit,boolean limitSpecified,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientGetInfo");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("offset",offset);
        soapReq.addProperty("offsetSpecified",offsetSpecified);
        soapReq.addProperty("limit",limit);
        soapReq.addProperty("limitSpecified",limitSpecified);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetInfo", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetInfo", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorInfoRecordXml resultVariable = new VectorInfoRecordXml(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }

    public void PatientLoginAsync(String insuranceNumber,String password) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientLoginAsync(insuranceNumber, password, null);
    }

    public void PatientLoginAsync(final String insuranceNumber,final String password,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, AuthtokenXml>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected AuthtokenXml doInBackground(Void... params) {
                return PatientLogin(insuranceNumber, password, headers);
            }
            @Override
            protected void onPostExecute(AuthtokenXml result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientLogin", result);
                }
            }
        }.execute();
    }

    public AuthtokenXml PatientLogin(String insuranceNumber,String password){
        return PatientLogin(insuranceNumber, password, null);
    }

    public AuthtokenXml PatientLogin(String insuranceNumber,String password,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientLogin");
        soapReq.addProperty("insuranceNumber",insuranceNumber);
        soapReq.addProperty("password",password);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientLogin", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientLogin", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    AuthtokenXml resultVariable =  new AuthtokenXml (j);
                    return resultVariable;

                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }

    public void PatientCheckRegisteredAsync(String insuranceNumber) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientCheckRegisteredAsync(insuranceNumber, null);
    }

    public void PatientCheckRegisteredAsync(final String insuranceNumber,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientCheckRegistered(insuranceNumber, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientCheckRegistered", result);
                }
            }
        }.execute();
    }

    public void PatientCheckRegistered(String insuranceNumber){
        PatientCheckRegistered(insuranceNumber, null);
    }

    public void PatientCheckRegistered(String insuranceNumber,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientCheckRegistered");
        soapReq.addProperty("insuranceNumber",insuranceNumber);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientCheckRegistered", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientCheckRegistered", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientLogoutAsync(AuthtokenXml authToken) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientLogoutAsync(authToken, null);
    }

    public void PatientLogoutAsync(final AuthtokenXml authToken,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientLogout(authToken, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientLogout", result);
                }
            }
        }.execute();
    }

    public void PatientLogout(AuthtokenXml authToken){
        PatientLogout(authToken, null);
    }

    public void PatientLogout(AuthtokenXml authToken,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientLogout");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientLogout", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientLogout", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientChangePasswordAsync(AuthtokenXml authToken,String password) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientChangePasswordAsync(authToken, password, null);
    }

    public void PatientChangePasswordAsync(final AuthtokenXml authToken,final String password,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientChangePassword(authToken, password, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientChangePassword", result);
                }
            }
        }.execute();
    }

    public void PatientChangePassword(AuthtokenXml authToken,String password){
        PatientChangePassword(authToken, password, null);
    }

    public void PatientChangePassword(AuthtokenXml authToken,String password,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientChangePassword");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("password",password);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientChangePassword", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientChangePassword", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientResetPasswordAsync(String insuranceNumber) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientResetPasswordAsync(insuranceNumber, null);
    }

    public void PatientResetPasswordAsync(final String insuranceNumber,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientResetPassword(insuranceNumber, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientResetPassword", result);
                }
            }
        }.execute();
    }

    public void PatientResetPassword(String insuranceNumber){
        PatientResetPassword(insuranceNumber, null);
    }

    public void PatientResetPassword(String insuranceNumber,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientResetPassword");
        soapReq.addProperty("insuranceNumber",insuranceNumber);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientResetPassword", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientResetPassword", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientSearchProviderByNameAsync(AuthtokenXml authToken,String providerNamePattern) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientSearchProviderByNameAsync(authToken, providerNamePattern, null);
    }

    public void PatientSearchProviderByNameAsync(final AuthtokenXml authToken,final String providerNamePattern,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, VectorServiceProviderXml>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorServiceProviderXml doInBackground(Void... params) {
                return PatientSearchProviderByName(authToken, providerNamePattern, headers);
            }
            @Override
            protected void onPostExecute(VectorServiceProviderXml result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientSearchProviderByName", result);
                }
            }
        }.execute();
    }

    public VectorServiceProviderXml PatientSearchProviderByName(AuthtokenXml authToken,String providerNamePattern){
        return PatientSearchProviderByName(authToken, providerNamePattern, null);
    }

    public VectorServiceProviderXml PatientSearchProviderByName(AuthtokenXml authToken,String providerNamePattern,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientSearchProviderByName");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("providerNamePattern",providerNamePattern);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientSearchProviderByName", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientSearchProviderByName", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorServiceProviderXml resultVariable = new VectorServiceProviderXml(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }

    public void PatientSearchProviderByCoordinatesAsync(AuthtokenXml authToken,String coordinates,int range,boolean rangeSpecified) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientSearchProviderByCoordinatesAsync(authToken, coordinates, range, rangeSpecified, null);
    }

    public void PatientSearchProviderByCoordinatesAsync(final AuthtokenXml authToken,final String coordinates,final int range,final boolean rangeSpecified,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, VectorServiceProviderXml>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorServiceProviderXml doInBackground(Void... params) {
                return PatientSearchProviderByCoordinates(authToken, coordinates, range, rangeSpecified, headers);
            }
            @Override
            protected void onPostExecute(VectorServiceProviderXml result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientSearchProviderByCoordinates", result);
                }
            }
        }.execute();
    }

    public VectorServiceProviderXml PatientSearchProviderByCoordinates(AuthtokenXml authToken,String coordinates,int range,boolean rangeSpecified){
        return PatientSearchProviderByCoordinates(authToken, coordinates, range, rangeSpecified, null);
    }

    public VectorServiceProviderXml PatientSearchProviderByCoordinates(AuthtokenXml authToken,String coordinates,int range,boolean rangeSpecified,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientSearchProviderByCoordinates");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("coordinates",coordinates);
        soapReq.addProperty("range",range);
        soapReq.addProperty("rangeSpecified",rangeSpecified);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientSearchProviderByCoordinates", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientSearchProviderByCoordinates", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorServiceProviderXml resultVariable = new VectorServiceProviderXml(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }

    public void PatientSearchProviderByAddressAsync(AuthtokenXml authToken,String address,int range,boolean rangeSpecified) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientSearchProviderByAddressAsync(authToken, address, range, rangeSpecified, null);
    }

    public void PatientSearchProviderByAddressAsync(final AuthtokenXml authToken,final String address,final int range,final boolean rangeSpecified,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, VectorServiceProviderXml>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorServiceProviderXml doInBackground(Void... params) {
                return PatientSearchProviderByAddress(authToken, address, range, rangeSpecified, headers);
            }
            @Override
            protected void onPostExecute(VectorServiceProviderXml result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientSearchProviderByAddress", result);
                }
            }
        }.execute();
    }

    public VectorServiceProviderXml PatientSearchProviderByAddress(AuthtokenXml authToken,String address,int range,boolean rangeSpecified){
        return PatientSearchProviderByAddress(authToken, address, range, rangeSpecified, null);
    }

    public VectorServiceProviderXml PatientSearchProviderByAddress(AuthtokenXml authToken,String address,int range,boolean rangeSpecified,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientSearchProviderByAddress");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("address",address);
        soapReq.addProperty("range",range);
        soapReq.addProperty("rangeSpecified",rangeSpecified);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientSearchProviderByAddress", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientSearchProviderByAddress", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorServiceProviderXml resultVariable = new VectorServiceProviderXml(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }

    public void PatientSearchProviderBySpecialityAsync(AuthtokenXml authToken,String speciality) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientSearchProviderBySpecialityAsync(authToken, speciality, null);
    }

    public void PatientSearchProviderBySpecialityAsync(final AuthtokenXml authToken,final String speciality,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, VectorServiceProviderXml>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorServiceProviderXml doInBackground(Void... params) {
                return PatientSearchProviderBySpeciality(authToken, speciality, headers);
            }
            @Override
            protected void onPostExecute(VectorServiceProviderXml result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientSearchProviderBySpeciality", result);
                }
            }
        }.execute();
    }

    public VectorServiceProviderXml PatientSearchProviderBySpeciality(AuthtokenXml authToken,String speciality){
        return PatientSearchProviderBySpeciality(authToken, speciality, null);
    }

    public VectorServiceProviderXml PatientSearchProviderBySpeciality(AuthtokenXml authToken,String speciality,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientSearchProviderBySpeciality");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("speciality",speciality);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientSearchProviderBySpeciality", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientSearchProviderBySpeciality", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorServiceProviderXml resultVariable = new VectorServiceProviderXml(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }

    public void PatientGetSpecialitiesAsync(AuthtokenXml authToken) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientGetSpecialitiesAsync(authToken, null);
    }

    public void PatientGetSpecialitiesAsync(final AuthtokenXml authToken,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, VectorString>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorString doInBackground(Void... params) {
                return PatientGetSpecialities(authToken, headers);
            }
            @Override
            protected void onPostExecute(VectorString result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientGetSpecialities", result);
                }
            }
        }.execute();
    }

    public VectorString PatientGetSpecialities(AuthtokenXml authToken){
        return PatientGetSpecialities(authToken, null);
    }

    public VectorString PatientGetSpecialities(AuthtokenXml authToken,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientGetSpecialities");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetSpecialities", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetSpecialities", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorString resultVariable = new VectorString(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }

    public void PatientGetAgendaAsync(AuthtokenXml authToken,String providerId) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientGetAgendaAsync(authToken, providerId, null);
    }

    public void PatientGetAgendaAsync(final AuthtokenXml authToken,final String providerId,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, VectorTimeslotXml>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorTimeslotXml doInBackground(Void... params) {
                return PatientGetAgenda(authToken, providerId, headers);
            }
            @Override
            protected void onPostExecute(VectorTimeslotXml result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientGetAgenda", result);
                }
            }
        }.execute();
    }

    public VectorTimeslotXml PatientGetAgenda(AuthtokenXml authToken,String providerId){
        return PatientGetAgenda(authToken, providerId, null);
    }

    public VectorTimeslotXml PatientGetAgenda(AuthtokenXml authToken,String providerId,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientGetAgenda");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("providerId",providerId);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetAgenda", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetAgenda", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorTimeslotXml resultVariable = new VectorTimeslotXml(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }

    public void PatientCreateAppointmentAsync(AuthtokenXml authToken,String timeslotId) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientCreateAppointmentAsync(authToken, timeslotId, null);
    }

    public void PatientCreateAppointmentAsync(final AuthtokenXml authToken,final String timeslotId,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientCreateAppointment(authToken, timeslotId, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientCreateAppointment", result);
                }
            }
        }.execute();
    }

    public void PatientCreateAppointment(AuthtokenXml authToken,String timeslotId){
        PatientCreateAppointment(authToken, timeslotId, null);
    }

    public void PatientCreateAppointment(AuthtokenXml authToken,String timeslotId,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientCreateAppointment");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("timeslotId",timeslotId);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientCreateAppointment", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientCreateAppointment", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientJoinWaitinglistProviderAsync(AuthtokenXml authToken,String providerId) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientJoinWaitinglistProviderAsync(authToken, providerId, null);
    }

    public void PatientJoinWaitinglistProviderAsync(final AuthtokenXml authToken,final String providerId,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientJoinWaitinglistProvider(authToken, providerId, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientJoinWaitinglistProvider", result);
                }
            }
        }.execute();
    }

    public void PatientJoinWaitinglistProvider(AuthtokenXml authToken,String providerId){
        PatientJoinWaitinglistProvider(authToken, providerId, null);
    }

    public void PatientJoinWaitinglistProvider(AuthtokenXml authToken,String providerId,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientJoinWaitinglistProvider");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("providerId",providerId);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientJoinWaitinglistProvider", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientJoinWaitinglistProvider", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientJoinWaitinglistSpecialityAsync(AuthtokenXml authToken,String speciality,String region) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientJoinWaitinglistSpecialityAsync(authToken, speciality, region, null);
    }

    public void PatientJoinWaitinglistSpecialityAsync(final AuthtokenXml authToken,final String speciality,final String region,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientJoinWaitinglistSpeciality(authToken, speciality, region, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientJoinWaitinglistSpeciality", result);
                }
            }
        }.execute();
    }

    public void PatientJoinWaitinglistSpeciality(AuthtokenXml authToken,String speciality,String region){
        PatientJoinWaitinglistSpeciality(authToken, speciality, region, null);
    }

    public void PatientJoinWaitinglistSpeciality(AuthtokenXml authToken,String speciality,String region,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientJoinWaitinglistSpeciality");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("speciality",speciality);
        soapReq.addProperty("region",region);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientJoinWaitinglistSpeciality", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientJoinWaitinglistSpeciality", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientGetAppointmentsAsync(AuthtokenXml authToken,String strartDate,boolean strartDateSpecified,String endDate,boolean endDateSpecified) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientGetAppointmentsAsync(authToken, strartDate, strartDateSpecified, endDate, endDateSpecified, null);
    }

    public void PatientGetAppointmentsAsync(final AuthtokenXml authToken,final String strartDate,final boolean strartDateSpecified,final String endDate,final boolean endDateSpecified,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientGetAppointments(authToken, strartDate, strartDateSpecified, endDate, endDateSpecified, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientGetAppointments", result);
                }
            }
        }.execute();
    }

    public void PatientGetAppointments(AuthtokenXml authToken,String strartDate,boolean strartDateSpecified,String endDate,boolean endDateSpecified){
        PatientGetAppointments(authToken, strartDate, strartDateSpecified, endDate, endDateSpecified, null);
    }

    public void PatientGetAppointments(AuthtokenXml authToken,String strartDate,boolean strartDateSpecified,String endDate,boolean endDateSpecified,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientGetAppointments");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("strartDate",strartDate);
        soapReq.addProperty("strartDateSpecified",strartDateSpecified);
        soapReq.addProperty("endDate",endDate);
        soapReq.addProperty("endDateSpecified",endDateSpecified);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetAppointments", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetAppointments", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientGetHospitalsByCoordinatesAsync(AuthtokenXml authToken,String coordinates,int range,boolean rangeSpecified) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientGetHospitalsByCoordinatesAsync(authToken, coordinates, range, rangeSpecified, null);
    }

    public void PatientGetHospitalsByCoordinatesAsync(final AuthtokenXml authToken,final String coordinates,final int range,final boolean rangeSpecified,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, VectorHospitalXml>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorHospitalXml doInBackground(Void... params) {
                return PatientGetHospitalsByCoordinates(authToken, coordinates, range, rangeSpecified, headers);
            }
            @Override
            protected void onPostExecute(VectorHospitalXml result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientGetHospitalsByCoordinates", result);
                }
            }
        }.execute();
    }

    public VectorHospitalXml PatientGetHospitalsByCoordinates(AuthtokenXml authToken,String coordinates,int range,boolean rangeSpecified){
        return PatientGetHospitalsByCoordinates(authToken, coordinates, range, rangeSpecified, null);
    }

    public VectorHospitalXml PatientGetHospitalsByCoordinates(AuthtokenXml authToken,String coordinates,int range,boolean rangeSpecified,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientGetHospitalsByCoordinates");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("coordinates",coordinates);
        soapReq.addProperty("range",range);
        soapReq.addProperty("rangeSpecified",rangeSpecified);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetHospitalsByCoordinates", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetHospitalsByCoordinates", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorHospitalXml resultVariable = new VectorHospitalXml(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }

    public void PatientGetHospitalsByAddressAsync(AuthtokenXml authToken,String address,int range,boolean rangeSpecified) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientGetHospitalsByAddressAsync(authToken, address, range, rangeSpecified, null);
    }

    public void PatientGetHospitalsByAddressAsync(final AuthtokenXml authToken,final String address,final int range,final boolean rangeSpecified,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, VectorHospitalXml>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorHospitalXml doInBackground(Void... params) {
                return PatientGetHospitalsByAddress(authToken, address, range, rangeSpecified, headers);
            }
            @Override
            protected void onPostExecute(VectorHospitalXml result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientGetHospitalsByAddress", result);
                }
            }
        }.execute();
    }

    public VectorHospitalXml PatientGetHospitalsByAddress(AuthtokenXml authToken,String address,int range,boolean rangeSpecified){
        return PatientGetHospitalsByAddress(authToken, address, range, rangeSpecified, null);
    }

    public VectorHospitalXml PatientGetHospitalsByAddress(AuthtokenXml authToken,String address,int range,boolean rangeSpecified,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientGetHospitalsByAddress");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("address",address);
        soapReq.addProperty("range",range);
        soapReq.addProperty("rangeSpecified",rangeSpecified);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetHospitalsByAddress", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetHospitalsByAddress", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorHospitalXml resultVariable = new VectorHospitalXml(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }

    public void PatientCancelAppointmentAsync(AuthtokenXml authToken,String appointmentId) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientCancelAppointmentAsync(authToken, appointmentId, null);
    }

    public void PatientCancelAppointmentAsync(final AuthtokenXml authToken,final String appointmentId,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientCancelAppointment(authToken, appointmentId, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientCancelAppointment", result);
                }
            }
        }.execute();
    }

    public void PatientCancelAppointment(AuthtokenXml authToken,String appointmentId){
        PatientCancelAppointment(authToken, appointmentId, null);
    }

    public void PatientCancelAppointment(AuthtokenXml authToken,String appointmentId,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientCancelAppointment");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("appointmentId",appointmentId);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientCancelAppointment", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientCancelAppointment", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientChangeAppointmentAsync(AuthtokenXml authToken,String appointmentId,String newTimeslotId) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientChangeAppointmentAsync(authToken, appointmentId, newTimeslotId, null);
    }

    public void PatientChangeAppointmentAsync(final AuthtokenXml authToken,final String appointmentId,final String newTimeslotId,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, Void>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected Void doInBackground(Void... params) {
                PatientChangeAppointment(authToken, appointmentId, newTimeslotId, headers);
                return null;
            }
            @Override
            protected void onPostExecute(Void result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientChangeAppointment", result);
                }
            }
        }.execute();
    }

    public void PatientChangeAppointment(AuthtokenXml authToken,String appointmentId,String newTimeslotId){
        PatientChangeAppointment(authToken, appointmentId, newTimeslotId, null);
    }

    public void PatientChangeAppointment(AuthtokenXml authToken,String appointmentId,String newTimeslotId,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientChangeAppointment");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("appointmentId",appointmentId);
        soapReq.addProperty("newTimeslotId",newTimeslotId);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientChangeAppointment", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientChangeAppointment", soapEnvelope);
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
    }

    public void PatientGetSurveysAsync(AuthtokenXml authToken,int surveyState,boolean surveyStateSpecified) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        PatientGetSurveysAsync(authToken, surveyState, surveyStateSpecified, null);
    }

    public void PatientGetSurveysAsync(final AuthtokenXml authToken,final int surveyState,final boolean surveyStateSpecified,final List<HeaderProperty> headers) throws Exception{

        new AsyncTask<Void, Void, VectorCustomerSurveyXml>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorCustomerSurveyXml doInBackground(Void... params) {
                return PatientGetSurveys(authToken, surveyState, surveyStateSpecified, headers);
            }
            @Override
            protected void onPostExecute(VectorCustomerSurveyXml result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("PatientGetSurveys", result);
                }
            }
        }.execute();
    }

    public VectorCustomerSurveyXml PatientGetSurveys(AuthtokenXml authToken,int surveyState,boolean surveyStateSpecified){
        return PatientGetSurveys(authToken, surveyState, surveyStateSpecified, null);
    }

    public VectorCustomerSurveyXml PatientGetSurveys(AuthtokenXml authToken,int surveyState,boolean surveyStateSpecified,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","PatientGetSurveys");
        soapEnvelope.addMapping("https://meetmdwcf.azurewebsites.net/API/XmlService.svc","authToken",new AuthtokenXml().getClass());
        soapReq.addProperty("authToken",authToken);
        soapReq.addProperty("surveyState",surveyState);
        soapReq.addProperty("surveyStateSpecified",surveyStateSpecified);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetSurveys", soapEnvelope,headers);
            }else{
                httpTransport.call("https://meetmdwcf.azurewebsites.net/API/XmlService.svc/IPatient/PatientGetSurveys", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorCustomerSurveyXml resultVariable = new VectorCustomerSurveyXml(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }

}
