package soap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.8.0
//
// Created by Quasar Development at 15-10-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class AppointmentResultsXml extends AttributeContainer implements KvmSerializable
{
    
    public AppointmentXml Appointment;
    
    public String Complains;
    
    public java.util.Date EditDate;
    
    public ArrayOfString HealthcareCodes=new ArrayOfString();
    
    public String Id;
    
    public String Info;
    
    public String SuggestedTreatment;

    public AppointmentResultsXml()
    {
    }

    public AppointmentResultsXml(Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("Appointment"))
        {	
	        Object j = soapObject.getProperty("Appointment");
	        this.Appointment = (AppointmentXml)__envelope.get(j,AppointmentXml.class);
        }
        if (soapObject.hasProperty("Complains"))
        {	
	        Object obj = soapObject.getProperty("Complains");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Complains = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Complains = (String)obj;
            }    
        }
        if (soapObject.hasProperty("EditDate"))
        {	
	        Object obj = soapObject.getProperty("EditDate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.EditDate = Helper.ConvertFromWebService(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof java.util.Date){
                this.EditDate = (java.util.Date)obj;
            }    
        }
        if (soapObject.hasProperty("HealthcareCodes"))
        {	
	        Object j = soapObject.getProperty("HealthcareCodes");
	        this.HealthcareCodes = new ArrayOfString(j,__envelope);
        }
        if (soapObject.hasProperty("Id"))
        {	
	        Object obj = soapObject.getProperty("Id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Id = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Id = (String)obj;
            }    
        }
        if (soapObject.hasProperty("Info"))
        {	
	        Object obj = soapObject.getProperty("Info");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Info = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Info = (String)obj;
            }    
        }
        if (soapObject.hasProperty("SuggestedTreatment"))
        {	
	        Object obj = soapObject.getProperty("SuggestedTreatment");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.SuggestedTreatment = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.SuggestedTreatment = (String)obj;
            }    
        }


    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Appointment!=null?this.Appointment:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Complains!=null?this.Complains:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.EditDate!=null? Helper.getDateTimeFormat().format(this.EditDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.HealthcareCodes!=null?this.HealthcareCodes:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Info!=null?this.Info:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.SuggestedTreatment!=null?this.SuggestedTreatment:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = AppointmentXml.class;
            info.name = "Appointment";
            info.namespace= "http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Complains";
            info.namespace= "http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "EditDate";
            info.namespace= "http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "HealthcareCodes";
            info.namespace= "http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Info";
            info.namespace= "http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SuggestedTreatment";
            info.namespace= "http://schemas.datacontract.org/2004/07/MeetMD.Models.DomainModel";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}
